// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ApiAuthUtec.Modelos;
using Microsoft.EntityFrameworkCore;

namespace ApiAuthUtec.Context;

public partial class DBAutenticadorContext : DbContext
{
    public DBAutenticadorContext(DbContextOptions<DBAutenticadorContext> options)
        : base(options)
    {
    }

    public virtual DbSet<cat_cuentas_autenticador_totp> cat_cuentas_autenticador_totps { get; set; }

    public virtual DbSet<usr_usuario> usr_usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<cat_cuentas_autenticador_totp>(entity =>
        {
            entity.HasKey(e => e.cat_codigo).HasName("PK__cat_cuen__38ABB93F60D16CE9");
        });

        modelBuilder.Entity<usr_usuario>(entity =>
        {
            entity.HasKey(e => e.usr_codigo).HasName("PK__usr_usua__9AB2F9C05F3FC318");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}