// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiAuth.Modelos;

[Table("cat_cuentas_autenticador_totp")]
public partial class cat_cuentas_autenticador_totp
{
    [Key]
    public int cat_codigo { get; set; }

    public int cat_codper { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string cat_cuenta { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string cat_clave { get; set; }
}